# Generated by Django 2.2.3 on 2019-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.URLField()),
                ('final_address', models.URLField(blank=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('check_date', models.IntegerField()),
                ('error_message', models.TextField(blank=True, max_length=400)),
            ],
        ),
    ]
