# Generated by Django 2.2.3 on 2019-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.CharField(max_length=200)),
                ('final_address', models.CharField(max_length=200)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('check_date', models.DateTimeField(verbose_name='check date')),
            ],
        ),
    ]
