# Generated by Django 2.2.3 on 2019-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_checker', '0003_auto_20190729_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='error_message',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
